projects:
  whatscrapp:
    schemaPath: >-
      home/harshit/Documents/personal/notJustDev/chat-app/WhatsappClone/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
